services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: heath_finance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: ../infra/Dockerfile.backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://admin:adminpassword@db:5432/heath_finance?schema=public"
      PORT: 3001
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
